# Generated by Django 5.0.1 on 2024-02-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
